version: '3'
volumes:
  database:

services:
  # Database for Historical Data
  rethinkdb:
    build: ./database
    privileged: true
    restart: always
    volumes:
      - 'database:/data'
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"

  # Message Queue for Periodic Tasks
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"

  # flask:
  #   build: ./server
  #   privileged: true
  #   tty: true
  #   restart: always
  #   volumes:
  #     - ./server:/app/server
  #   ports:
  #     - 5000:5000
    # links:
    #   - rethinkdb:db
      
  # app:
  #   build: ./app
  #   privileged: true
  #   restart: always
  #   # depends_on:
  #   #   - rethinkdb
  #   ports:
  #     - "80:80"
  #     - "443:443"
