version: '2'
services:
  rethinkdb:
    build: ./rethinkdb
    privileged: true
    restart: always
    ports:
      - "8080"
      - "28015"
      - "29015"
  app:
    build: ./app
    privileged: true
    restart: always
    depends_on:
      - rethinkdb
    expose:
      - "80"
      - "443"
